### ISSUE TITLE
[Question] Dynamic SharedTypes enumeration

### ISSUE THREAD

**Issue by Andale-online** [natemcmaster/DotNetCorePlugins#106]
Hi again,

I really need the SharedTypes feature. Is there any way to enumerate these automatically? I don't know what assemblies may be loaded as plugin and I don't want the end user to specify every shared type. My idea is to scan for SharedTypes and map them automatically.
 Just wanted to ask before I start developing this. If not can you give me a push in the right directions?

**Comment by natemcmaster** [comment]
Currently, shared types need to be present in the host for them to work properly, and must be defined before any plugins are loaded. If you want to always use shared types from the host app, you can specify `PreferSharedTypes = true` instead of listing all of them explicitly.

```csharp
PluginLoader.CreateFromAssemblyFile("./plugins/MyPlugin/MyPlugin1.dll",
    config => config.PreferSharedTypes = true);
```

That said, it sounds like you are trying to allow plugins to define shared types, is that right? If so, we need to have a larger design discussion about how this would work before diving into any kind of implementation. Sharing context between plugins is going to be challenging to expose to users in a sensible API because it probably require multiple levels of AssemblyLoadContext's. Managing dependencies between multiple contexts isn't something I've seen done and haven't found a compelling need for it any of my projects.
