### ISSUE TITLE
Dependent assemblies fail to load from within Razor Views

### ISSUE THREAD

**Issue by plioi** [natemcmaster/DotNetCorePlugins#25]
**Describe the bug**
Modifying the MVC sample to reference an assembly like AutoMapper, interacting with the assembly from a controller works, while interacting with the assembly from a View fails to load the dependent assembly.

**To Reproduce**

1) Start with the MVC sample here: https://github.com/natemcmaster/DotNetCorePlugins/tree/abf20cdaacebb1d691df3ed5aa18d22892f5a48a/samples/aspnetcore-mvc
2) Aside: I had to modify MvcApp.csproj's publish in order for the plugin to successfully publish.
3) From a controller, interact with typeof(IMapper).Assembly. Expect success.
4) From a view, interact with typeof(IMapper).Assembly. Fails to load the assembly that was successfully loaded in step 3.

**Additional context**

Modification to MvcApp.csproj:

```xml
  <Target Name="PublishPlugins" BeforeTargets="Build">

    <ItemGroup>
      <PluginProject Include="..\MvcAppPlugin1\MvcAppPlugin1.csproj" />
    </ItemGroup>

    <MSBuild Projects="@(PluginProject)" Targets="Publish" Properties="Configuration=$(Configuration);PublishDir=$(TargetDir)plugins\%(FileName)\" />
  </Target>
```

Modified MyPluginController action:

```cs
        public IActionResult Index()
        {
            ViewData["AutoMapperVersion"] = typeof(IMapper).Assembly.GetName().ToString();

            return View();
        }
```

Modified MvcAppPlugin1\Views\MyPlugin1\Index.cshtml
```cs
@using AutoMapper
@{
    ViewData["Title"] = "Plugin1";
}

<p>Plugin 1</p>
<div>Referencing AutoMapper from controller action: @ViewData["AutoMapperVersion"]</div>
<div>Referencing AutoMapper from a view: @(typeof(IMapper).Assembly.GetName().ToString())</div>
```

If I remove the final line of the view, the app successfully shows the assembly name determined by the controller. If I leave it in place, we fail to load AutoMapper:

![image](https://user-images.githubusercontent.com/652745/50715034-d7717880-1040-11e9-8a38-0be0e30f7f6d.png)

Does this look like a misuse of the plugin library? Is there an additional step I should take so that work performed in views can successfully work with a plugin's own dependencies?

**Comment by plioi** [comment]
Another symptom of possibly-the-same root issue is that a custom View Model defined within the plugin cannot be used as the `@model` of a View. The plugin assembly cannot be found at runtime.

**Comment by natemcmaster** [comment]
Thanks for reporting. There were two problems.

1. The sample didn't load related assemblies (e.g. the Views assembly) correctly. MVC's `RelatedAssemblyAttribute.GetRelatedAssemblies` API calls `Assembly.LoadFile` under the hood, which creates its own unique load context and bypasses the plugin's assembly resolution logic.
2. The implementation of assembly resolution always skipped assemblies which were not predefined in .deps.json (or programmatically with AssemblyLoadContextBuilder.) I added a change so that when all else fails, the loader tries to find assemblies in the plugin's base directory.

Give this a shot and let me know if it works: https://www.myget.org/feed/natemcmaster/package/nuget/McMaster.NETCore.Plugins/0.2.2-rtm.41
