### ISSUE TITLE
Api call in controller not found after loading the assembly at runtime.

### ISSUE THREAD

**Issue by Chris197** [natemcmaster/DotNetCorePlugins#38]
Hi Nate,

Thanks for sharing this project, I'd really like to get a plugin architecture working in our projects. Also, congrats on your newborn! (yes I read the other issues ;-)). 

I have tried using your library to perform a really simple task: Load an assembly at runtime containing a controller to include the calls from that controller, without having to reference that assembly at compile time. 

I have reproduced the issue in a simple sample project here: https://github.com/Chris197/applicationparttest

Any idea what's wrong?

Regards,

Chris

UPDATE: 

I have just found that replacing this code:

`PluginLoader.CreateFromAssemblyFile(path).LoadDefaultAssembly();`

with this:

`AssemblyLoadContext.Default.LoadFromAssemblyPath(path);`

does work. So the problem does seem to be related to the PluginLoader.

**Comment by natemcmaster** [comment]
> congrats on your newborn!

Thank you!

You're repro is basically doing what I had in my sample: https://github.com/natemcmaster/DotNetCorePlugins/blob/master/samples/aspnetcore-mvc/MvcApp/Startup.cs#L23-L33. Last time I checked, the sample still worked.

If AssemblyLoadContext.Default.LoadFromAssemblyPath is working and PluginLoader is not, then the most likely cause is that your plugin has a _private_ version of the MVC dependency, which means types may not unify between the hosting app's version of MVC and the plugin. Try changing your code to `PluginLoader.CreateFromAssemblyFile(path, PluginLoaderOptions.PreferSharedTypes)`

**Comment by Chris197** [comment]
Adding 'PluginLoaderOptions.PreferSharedTypes' solves the problem, thanks!

Though, I'm not quite sure I understand what you mean by:

> the most likely cause is that your plugin has a _private_ version of the MVC dependency

I'm comparing the code to your sample (on which it was based), but I don't see a difference.

**Comment by natemcmaster** [comment]
There are multiple versions of Microsoft.AspNetCore.Mvc.dll. Version 2.1.1, 2.1.2, etc. Normally (when not doing plugin type stuff), this isn't an issue because there is only one folder of dll's and you can only have one file named Microsoft.AspNetCore.Mvc.dll in that folder. The .NET SDK will figure out for you which version to use.

Plugins introduce a new quirk. You might have multiple copies of Microsoft.AspNetCore.Mvc.dll in various plugin folders. Which one should be used? `PluginLoaderOptions.PreferSharedTypes` tells the plugin system to use the same version of Mvc.dll between all plugins and the app host, if possible. Sharing types is the default behavior of `AssemblyLoadContext.Default.LoadFromAssemblyPath`, but not `PluginLoader`.

Glad we figured it out. I'll update the MVC sample in this repo.
