### ISSUE TITLE
Add a MEF catalog using this loader

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/DotNetCorePlugins#4]
Implement `ComposablePartCatalog` using the assembly load context loader.

**Comment by nathanaw** [comment]
I started a fork of this repo to experiment with a MEF catalog. Would appreciate any feedback...
https://github.com/nathanaw/DotNetCorePlugins/tree/mef-plugin-sample

See the new "MEF sample" here:
https://github.com/nathanaw/DotNetCorePlugins/tree/mef-plugin-sample/samples/mef

### Main points:

1. There is a [PluginCatalog](https://github.com/nathanaw/DotNetCorePlugins/blob/mef-plugin-sample/samples/mef/MefWebApp/Mef/PluginCatalog.cs) that uses the DotNetCorePlugins library to load exports from the other DLLs.
2. I found that the PluginCatalog needed to include the MEF attributes in the SharedTypes list in order for MEF to properly locate and load the exports in the plugins.
3. The plugins are about a simple scenario of a "pipeline" that can manipulate a string value in a series of plug-able steps. The plugin uses some features of MEF to help demonstrate a few things that are harder to accomplish with a straight DI / IoC approach.
4. The pipeline is used in the [HomeController](https://github.com/nathanaw/DotNetCorePlugins/blob/mef-plugin-sample/samples/mef/MefWebApp/Controllers/HomeController.cs) and the display logic is in the [shared _Layout.cshtml view](https://github.com/nathanaw/DotNetCorePlugins/blob/mef-plugin-sample/samples/mef/MefWebApp/Views/Shared/_Layout.cshtml).

### Main questions:

1. Is this approach on the right path for using these together?
2. Are there clear benefits to using these together over what MEF provides out of the box in .NET Core?
3. Does it make sense to formalize the catalog class into package, or does it seem best to leave this as a simple "copy/paste" bit of sample code?

Thanks!

**Comment by natemcmaster** [comment]
This looks great! The PluginCatalog class is pretty much exactly what I was hoping to create. 

I think a sample is a good place to begin. The code itself isn’t all that big, so I’m not sure it needs to be its own package yet. 

It might be good to also create a minimal sample. For .NET devs unfamiliar with aspnetcore, the  aspnet sample may be a bit heavy. The important piece is the PluginCatalog.

**Comment by dazinator** [comment]
> Are there clear benefits to using these together over what MEF provides out of the box in .NET Core?

I'd love to see this explored further. Perhaps the sample can be bought into this repo?

Here are some pain points which caused me to consider MEF, but I am not settled on it yet.

1. The use of Activator.CreateInstance() [as seen here]( https://github.com/natemcmaster/DotNetCorePlugins/blob/master/samples/aspnetcore/MainWebApp/Startup.cs#L37) - what if plugins require dependencies to be injected?

2. What if plugin A requires a service which is supplied by plugin B, rather than supplied by the host?

3. What if plugin A requires a service which is supplied by plugin B, but the version of plugin B that plugin A was compiled against, is different from the version of plugin B supplied at runtime? - Can plugin A ensure it gets the exact version of plugin B that it was compiled against - perhaps by bundling that copy of the .dll with its own? Would MEF know how to handle this situation?

**Comment by natemcmaster** [comment]
If you're volunteering to write a sample and contribute, I'd be happy to review and accept it. Otherwise, this will stay closed because I'm not planning to take action on this.
