### ISSUE TITLE
Assembly loading doesn't work as expected

### ISSUE THREAD

**Issue by godrose** [natemcmaster/DotNetCorePlugins#41]
**Describe the bug**
Loading the assembly from its path creates types differently from expected

**To Reproduce**
1. Using this version of the library '0.2.4'
2. Run tests from https://github.com/godrose/netcore-load
3. See the error in the test which uses the package as opposed to `Assembly.LoadFrom` approach

**Expected behavior**
Tests should be green in both cases

**Screenshots**
Irrelevant

**Additional context**
.NET Core pre-3.0, VS 2017, Test Explorer

**Comment by natemcmaster** [comment]
Interesting. Spent a little time debugging. My implementation of [AssemblyLoadContext ](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-2.2)is doing what I expect and behaving the way I want it to. I'm not sure why your type comparisons in `.IsCompositionModule` aren't working as expected. Does the result change in you strong-name your libraries? System.Runtime.Loader might be taking that into account when creating type identities.

By the way, the behavior you are seeing is sort of by-design. From the README (emphasis added)

> 
> This project provides API for loading .NET Core assemblies dynamically, executing them as extensions to the main application, and **finding and isolating the dependencies of the plugin from the main application**.
> 
> Unlike other approaches to dynamic assembly loading, like **Assembly.LoadFrom**, this API attempts to imitate the behavior of .deps.json and runtimeconfig.json files to probe for dependencies, load native (unmanaged) libraries, and to find binaries from runtime stores or package caches. In addition, it allows for **fine-grained control over which types should be unified between the loader and the plugin, and which can remain isolated from the main application.**

One the knobs you can use to control isolation is the `preferSharedTypes` option. E.g.
```
PluginLoader.CreateFromAssemblyFile(assemblyFile, PluginLoaderOptions.PreferSharedTypes);
```

Give that a shot - I think it will fix your test.

**Comment by godrose** [comment]
@natemcmaster Thanks for the reply. I haven't tested the strong-name case because I won't add strong-name to the release version in any case. 
Your suggestion has helped. It looks like the docs should be updated to reflect this use case.
Thanks again for your effort!

**Comment by godrose** [comment]
@natemcmaster Please pay attention that this method is absent from the `0.3.0-beta24` package which introduces regression. What's the recommended workaround if any?
Thanks.

**Comment by natemcmaster** [comment]
Yeah, I was contemplating removing that method in the next major release of this package. The nightly builds of the package should be considered unstable as I'm still playing around with some API changes.

**Comment by natemcmaster** [comment]
@godrose I restored the PluginLoaderOptions API, but made it obsolete. The recommended replacement in the nightly betas would be this:
```c#
PluginLoader.CreateFromAssemblyFile(assemblyFile, config => config.PreferSharedTypes = true);
```

**Comment by godrose** [comment]
@natemcmaster Still the process fails during the runtime. Something with the loading is different from the way it works when the assemblies are referenced.
I use the latest nightly 0.3.0-beta26

**Comment by godrose** [comment]
@natemcmaster See Samples.Specifications.Server.sln in the https://github.com/godrose/netcore-load

**Comment by natemcmaster** [comment]
Saw your comment. I have fairly limited time to work on the project. I'm marking this as a bug  that requires more investigation to determine the cause and recommended fix. Help appreciated if you can spare time!

**Comment by jzabroski** [comment]
@natemcmaster What I really want for assembly loading is to literally just pass in .deps.json to a method and then a white listing function of assemblies (and their transitive dependencies) I *do* want to load.

This would solve some problems for me today, such as when bootstrapping IoC in a PowerShell module through IModuleAssemblyInitializer.  Effectively, it's solving an "air space" issue between the fact CIL will lazy load assemblies as it encounters types found in those assemblies, and `AppDomain.CurrentDomain.GetAssemblies()`.  I want `.deps.json` to be my intermediate format for how to do the phase of dependency injection bootstrapping that scans assemblies for types to map into scope rules.

I say this, because @godrose maintains `Solid.Practices.Modularity`, which performs a topological sort to determine module loading order using a bit hacky IHaveDependencies interface which is really just an array of strings (https://github.com/godrose/Solid/blob/89bcd29da7d07846a4dd59883073f9841aa2ac19/Solid.Core/IHaveDependencies.cs). - Unless I'm missing something, that's exactly what .deps.json gives you, too, so why not just use .deps.json as the argument to `PluginLoader`?

**Comment by jzabroski** [comment]
Another thought would be, similar to how Maven has a [`dependency:analyze` plugin goal](https://maven.apache.org/plugins/maven-dependency-plugin/analyze-mojo.html), is to simply split out the responsibilities of loading things into an `AssemblyLoadContext` from the analysis of possible `AssemblyLoadContext` "participants".

I don't quite like the way Java does this: I think the way Maven works and the whole POM is actually wrong but "good enough" that most engineers are blind to the warts it represents:

- Does not separate `compile-time` from `run-time` tasks. `dependency-analyze` DependsOn `test-compile`.  There should be a natural dual `test-run`.  In .NET, this would be using Roslyn to read the dll without actually invoking any static constructors, thus ensuring safe "test-run" semantics.
- The goal outcomes of "used and declared"; "used and undeclared"; "unused and declared" are prone to false positives in cases of extreme modularity.  For totally modular scenarios like hot-swapping implementations (like dropping in a different Rules.dll into an app with a RulesEngine.dll execution engine and RulesContracts.dll that defines the contracts for the Rules.dll and RulesEngine.dll to work parsimoniously)

**Comment by godrose** [comment]
@jzabroski Hey there. The main idea behind the `IHaveDependencies` is to, well, model an entity which has dependencies. Right now the dependencies are presented by their ids only but this can change. That's why I created the wrapper interface.
That aside I've been trying to make the dynamic loading work in .NET Core for some time now and it behaves differently in various setups. Still trying to figure out what exactly is going on

**Comment by jzabroski** [comment]
@godrose Have you considered using Fody and weaving into:

* Each assembly, [.moduleinit (not CLS compliant)](https://github.com/Fody/ModuleInit): `System.Console.WriteLine("AssemblyName");`
* Each static class constructor, `System.Console.WriteLine($"{nameof(MyClass)}");`

Separately, @natemcmaster explained to me last night, [via his blog](http://disq.us/p/22pooja), that it is possible to load .deps.json at run-time via: `System.AppContext.GetData("APP_CONTEXT_DEPS_FILES")`.  He also explained to me that a typical .NET Core app will have multiple .deps.json (which is news to me, since I've been doing .NET Core for 2 years now and only use the default one and have never needed `dotnet --additional-deps`.  However, it is nice touch and eloquently solves some problems that I feel are basically wrong with Maven and its POM (and the Super POM).

**Comment by jzabroski** [comment]
By the way, in JavaScript, whitelisting depedencies is called "[tree shaking](https://webpack.js.org/guides/tree-shaking/)".  The use case is not precisely one-to-one, but it is pretty close.

**Comment by natemcmaster** [comment]
Hey there, just letting you know I'm listening. I'm on vacation for 2 weeks without a laptop, so don't have time to investigate some of the solutions proposed. If you come up with something, let me know and I'll take a closer look when I'm home.

**Comment by jzabroski** [comment]
Hey Nate! Would love the chance to work with a great engineer like you on something. But I'm admittedly t-minus 28 days til my mandatory two weeks vacation at work, then honey moon for two weeks.

Enjoy your vacation, too.  We can circle back around August 18th when I'm back in the states.  If I even bring my phone my wife will throw it off  the boat! LOL

**Comment by natemcmaster** [comment]
@jzabroski congrats on the wedding and enjoy your honeymoon! I'm available to help whenever you're ready to proceed on this issue.

**Comment by jzabroski** [comment]
BTW,

> System.Runtime.Loader might be taking that into account when creating type identities.

Type identity is not based on strong naming but type load order.  Create classes F, U, B, A, R and load them in different orders and you will see what I mean.

The "obvious" solution is what Autofac and some DI containers do: Create a type that wraps the type you want to instantiate.  In effect it's a lightweight Service Locator that lets you determine to the type level the sequence in which the CLR loads your types.  In Autofac, this is called the Meta type.  I recommend rolling your own Meta type with more domain-specific encapsulate, e.g. `ITaskDefinition<T> where T : ITask` is a LOT easier to read (and extend) than `Meta<Task>`

**Comment by jzabroski** [comment]
Here is a reference by ex-Microsoft C# compiler engineer, Eric Lippert, as additional food for thought; https://stackoverflow.com/a/8360958/1040437

As Eric says, COM is a convention where once you label a "record of functions" with a particular GUID, that contract must stay forever. In many ways, COM is the weak predecessor to the modern merkle tree/hash tree conventions used in "proof of work" libraries/projects like NixOS, Bazel, Bitcoin and Ethereum today...

**Comment by jzabroski** [comment]
Tangential topic: Registration-free COM Interop test case, as discussed in https://github.com/dotnet/core-setup/issues/4314 and https://docs.microsoft.com/en-us/dotnet/framework/interop/registration-free-com-interop but coming with full support in .NET Core 3.0

Further, may need to think of a "COM jail" approach to avoid [abusing registration-free COM](https://inquest.net/blog/2019/5/30/abusing-registration-free-com):

> In this short post, we dissect the inner workings of registration-free COM interop and present a known technique that red teamers can abuse to dynamically load .NET assembly logic. This technique was first presented by Casey Smith. Additionally, some minor obfuscated variations are presented in hopes of evading existing detection mechanisms. Proof-of-concept code snippets are provided in both PowerShell and JScript to demonstrate versatility.

**Comment by natemcmaster** [comment]
Ok, back to the original point of this thread....I identified the cause of the issue. The problem was how transitive dependencies of shared types were being handled. The fix is pretty simple, and I validated that it makes tests pass in https://github.com/godrose/netcore-load/tree/c341c9e2c447a7bf75db377cda9d4551eefd3be6.

@jzabroski the ideas you mentioned above are interesting and I want to make sure they are given proper follow up, but I've lost track a little bit of what is being proposed. Can you open a new thread to discuss further?

**Comment by jzabroski** [comment]
@natemcmaster I've done as you suggested. Nice job finding that bug!

**Comment by godrose** [comment]
@natemcmaster I'm not sure whether to file a new issue as it seems very similar to the one you closed.
Use this repo
https://github.com/godrose/netcore-load/tree/master
and observe how reverting the changes from the commit https://github.com/godrose/netcore-load/commit/d5e945c1b7f6f5b54faf5d25f19ff1056871bf22 would fail the [](api/warehouse) call.
This functionality works in one of the old pre-release packages, 0.3.0-beta.36, for example.

**Comment by natemcmaster** [comment]
New issue, if you don't mind.
