### ISSUE TITLE
Add Controller from Plugin in .NET Core 3 doesn`t work as expected

### ISSUE THREAD

**Issue by ThorstenWeiss** [natemcmaster/DotNetCorePlugins#43]
**Describe the bug**
I use your code with net core 3 preview 6, and the plugin is loaded.
But no controller from the plugin is loaded or not visible in swagger. Only the controller from
the api are loaded and accessable.

**To Reproduce**
1. Using your example of net core 3 webapi.
1. Using this version of the library '0.3.0-beta.26'
2. Add this code to your startup function:
```c#
var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(pluginDll);
foreach(var type in assembly.GetTypes())
{
    if (typeof(Controller).IsAssignableFrom(assembly.GetType(type.FullName)))
    {
        this._logger.LogDebug(" + Controller: " + type.FullName);
        services.AddMvc().AddApplicationPart(assembly).AddControllersAsServices();
    }
}
```
3. See what happen

**Expected behavior**
The Controller is visible in swagger and the endpoint is usable.

**Additional context**
.NET Core pre-3.0 preview 6, VS 2019, Chrome

**Comment by natemcmaster** [comment]
Thanks for opening the issue. I'm heading out on a long trip, so won't be able to investigate more right now, but this looks like something that needs more investigation. If you're able to identify what is wrong, I'd appreciate the help.

**Comment by natemcmaster** [comment]
Btw, I [updated my MVC sample](https://github.com/natemcmaster/DotNetCorePlugins/commit/85a4c87dc6a5566e8d480f87efe50f2399146790) to .NET Core 3, and things appear to work just fine. Can you try updating your code to use `ApplicationPartFactory` instead of `AddApplicationPart()`? See https://github.com/natemcmaster/DotNetCorePlugins/blob/85a4c87dc6a5566e8d480f87efe50f2399146790/samples/aspnetcore-mvc/MvcApp/Startup.cs#L14-L54

**Comment by ThorstenWeiss** [comment]
thanks, works fine.
