### ISSUE TITLE
CreateFromAssemblyFile obsolete

### ISSUE THREAD

**Issue by LaterStart** [natemcmaster/DotNetCorePlugins#57]
Hi,

I'm currently successfully using this method overload which seems to go obsolete from this version.

`PluginLoader.CreateFromAssemblyFile(Path.GetFullPath(path), null, PluginLoaderOptions.PreferSharedTypes)`

I have tried to use without loader options, but unsuccessfully. What do you recommend?

**Comment by natemcmaster** [comment]
I decided to obsolete `PluginLoaderOptions` because the number of options for the loader is growing, and an enum doesn't seem suitable anymore. For example, in the .NET Core 3 release, I'm adding support for reloading plugins, and another contributor is working on hot reloading.

Try replacing your code with one of these:
```c#
var loader = PluginLoader.CreateFromAssemblyFile(assemblyFile, config => config.PreferSharedTypes = true);
```

**Comment by LaterStart** [comment]
Yes, configuration seems more suitable to .net core philosophy :)
It solved the problem, thanks!
