### ISSUE TITLE
Loading the assembly requires having reference to its interface-containing assembly as well

### ISSUE THREAD

**Issue by godrose** [natemcmaster/DotNetCorePlugins#78]
**Describe the bug**
The assembly containing the implementation for the contract (interface) can't be done without explicitly referencing 
the assembly which contains the definition of the contract (interface)

**To Reproduce**
1. Using this version of the library '0.3.0'
2. Add breakpoint inside ``
2. Run `Facade` project from
https://github.com/godrose/netcore-load/tree/master
3. Hit [localhost:32064/api/warehouse](url)

**Expected behavior**
Call is handled successfully

**Actual behavior**
`IWarehouseRepository` implementation can't be located

**Notes**
Observe how reverting the changes from the commit godrose/netcore-load@d5e945c would fail the call.
This functionality also works in one of the old pre-release packages, 0.3.0-beta.36, for example.

**Additional context**
.NET Core 3.0, VS 2019, Test Explorer

**Comment by natemcmaster** [comment]
There are two facade projects in your repro. I'm not exactly sure what I'm looking for.

**Comment by godrose** [comment]
@natemcmaster You're right. Use `SomeAssembly.Facade` as it's much clearer what's going on there.

**Comment by natemcmaster** [comment]
I read the code and I'm still not 100% I understand what you're trying to do, but it appears to me that at least one problem is that you're creating a unique assembly loader per .dll here: https://github.com/godrose/netcore-load/blob/b09327732a891b174b83e9ef8e6c453a56abfc3f/Samples.Specifications.Server.Facade/Startup.cs#L26-L29

I think there may be a general misunderstanding here of how `PluginLoader` is supposed to be used. Generally, each plugin should be in a directory of its own with the plugin's dependency .dll's in that same directory. Easiest way to prepare a plugin is with `dotnet publish`. See https://github.com/natemcmaster/DotNetCorePlugins#the-host for a more detailed description.

**Comment by godrose** [comment]
@natemcmaster 
So the general idea in my example is to have all plugins compiling in the same directory. It is the solution configuration which will decide whether the specific plugin is eventually built. This is useful for the cases where I would like to substitute implementations of a particular interface and test the app behavior.
I examined the example you provided within the link. It states that each assembly file indeed has its own loader
```
var loader = PluginLoader.CreateFromAssemblyFile(
                    pluginDll,
                    sharedTypes: new [] { typeof(IPlugin) });
                loaders.Add(loader);
```
So I don't really see how it's different from what I'm doing.
The question here is what happens if you use
```
var loader = PluginLoader.CreateFromAssemblyFile(
                    pluginDll,
                    config => config.PreferSharedTypes = true);
                loaders.Add(loader);
```
instead and remove the explicit reference to the project containing the `IPlugin` interface. 
Will it still work? Should it?

**Comment by natemcmaster** [comment]
The distinction I was trying to make was that 1 plugin = 1 plugin loader. There might be multiple assemblies per plugin, but you should still only use 1 instance of PluginLoader. The assembly you pass to PluginLoader is the "entry" assembly, also called the "default" assembly. All dependencies of the default assembly will be found and loaded by PluginLoader. Normally, the dependencies of the plugin sit in a directory next to the default assembly.

Because you are sharing a common directory and creating multiple loaders from the same directory, you might have multiple instances of Samples.Specifications.Server.Domain.dll loaded. `PreferSharedTypes` only handles sharing between the host and the plugin, not between multiple plugins, so this might be why 
you're code is having trouble finding implementations of IWarehouseRepository.
