### ISSUE TITLE
How can I add JS and CSS files to the plug-in?

### ISSUE THREAD

**Issue by ljq021** [natemcmaster/DotNetCorePlugins#85]

**Comment by natemcmaster** [comment]
Plugins don't do anything special with the filesystem, so do it the same way you would add files to a regular .NET project.

**Comment by olle-j** [comment]
This is more or less possible to do using Microsoft.Extensions.FileProviders.Embedded.

Add the following to your plugin.csproj:
```
  <PropertyGroup>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="3.0.1" />
  </ItemGroup>
```

I added a file test.html to the Resources directory under my plugin. It may be a good idea to use unique names on this directory to make sure it doesn't collide with other plugins (Plugin1/Resources). This process makes sure we add all our resources to the plugin-dll and a manifest with a list of the files will be created out of the box.

I also added the following to my web project:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="3.0.1" />
  </ItemGroup>
```

Ok. Now we need to create instances of IFileProvider that maps to our plugin. We also want to keep the original WebRootFileProvider since our plugins will not be alone resolving static resources.

I refactored the MvcPluginExtensions class a bit.

```
var plugins = new List<Assembly>();
...
var pluginAssembly = pluginLoader.LoadDefaultAssembly();
plugins.Add(pluginAssembly);
```

Now we have a list of all the plugin assemblies. Now we need to update the WebRootFileProvider.
```
var allProviders = new List<IFileProvider>();
// Keep the existing provider
allProviders.Add(_env.WebRootFileProvider);
// Add a manifest provider for each plugin
allProviders.AddRange(plugins.Select(p => new ManifestEmbeddedFileProvider(p)));

// Replacing the previous WebRootFileProvider by our new composite one
_env.WebRootFileProvider = new CompositeFileProvider(allProviders);
```

This is a bit tricky to do since the loading of the assembly are made in an extension method and the updating of the WebRootFileProvider are best done somewhere else. I just refactored (moved) this extension method to be a part of my Startup.ConfigureServices, since I want my plugins to be able to register services anyway..
