### ISSUE TITLE
[need help] plugin.LoadDefaultAssembly() lock an assembly. How can I do change this?

### ISSUE THREAD

**Issue by GENiALi** [natemcmaster/DotNetCorePlugins#87]
After run this code I can't delete the assembly. How I can change this behavior?

```csharp
using (PluginLoader plugin = PluginLoader.CreateFromAssemblyFile(assembly.FullName, sharedTypes: new[] { typeof(IPlugin) }))
{
    Type type = plugin.LoadDefaultAssembly().GetTypes().FirstOrDefault(t => typeof(IPlugin).IsAssignableFrom(t) && !t.IsAbstract);

    if (type != null)
    {
        IPlugin activatedPlugin = (IPlugin)Activator.CreateInstance(type);
        DirectoryInfo di = new DirectoryInfo(assembly.FullName);
        activatedPlugin.InitSettings(di.Parent.FullName);
    }
}
```
After this code it should possible delete the assembly.

**Comment by zHaytam** [comment]
This also happens when I try the Hot reload example. Should I open a separate issue? If the dll is locked, you can't recompile a new version :/

**Comment by GENiALi** [comment]
Yes please, you can create a separate issue. You have any solution/idea for this problem? 

My project works great with this library and Hangfire. Only delete assebly after the first call, that don't work at the moment.

**Comment by natemcmaster** [comment]
This behavior is not configurable because the lower-level assembly loading APIs used in this library (the ones provided by .NET Core itself) do not offer a way to change this behavior. Once an assembly is loaded into a process for use, it is locked until that process exist.

This library attempts to workaround when hot reloading is enabled by reading the entire assembly from disk and loading into memory, but as noted, this doesn't always work. Also, this approach causes memory leaks so is not recommended in production.

**Comment by zHaytam** [comment]
But then how is hot reloading useful if we can't replace the dll?

**Comment by natemcmaster** [comment]
@zHaytam I'm not entirely sure why it doesn't always work, but my hunch is one process is trying to write to the file while the other is reading.

**Comment by natemcmaster** [comment]
I have released two updates since my last comment on this thread. Update 0.3.2 addressed issues with hot reloading.

@GENiALi - does using hot reload address your concern?

https://github.com/natemcmaster/DotNetCorePlugins/blob/370d3558e675e195728d02df5c9bf2f59d258a51/samples/hot-reload/HotReloadApp/Program.cs#L13-L14
